
export const works = [
  {
    id: 1,
    title: "Gemini謹製 夏のひまつぶしコレクション",
    description: "夏休みといえば？そう、暇。とにかく暇。その暇潰しの一助となるサイト。数多くのミニゲームを遊ぶことができます。楽しさを求めず、ただ時間をつぶしたい人向け。本当にしょうもないゲームをたくさん制作しました。",
    imageUrl: "/gemini_hima.jpg",
    imageUrl_sp: "/gemini_hima_s.png",
    externalUrl: "https://himatubusi.pages.dev/",
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: 2,
    title: "Todo App",
    description: "シンプルなTodoアプリ。非常にシンプルながら欲しい機能は揃っています。フィルター機能も搭載し、全てのタスク、未完了のタスク、完了済みのタスクを簡単に切り替えられます。",
    imageUrl: "/todo_app.png",
    imageUrl_sp: "/TodoApp_s.png",
    externalUrl: "https://todo-app-d6h.pages.dev/",
    technologies: ["React", "TypeScript", "Create React App", "Jest & React Testing Library", "CSS"],
  },
  {
    id: 3,
    title: "Memo Pad",
    description: "このメモ帳アプリは、シンプルな操作でメモを作成・編集できるのはもちろん、Firebase 認証を活用して端末をまたいだ同期まで自動で行ってくれるクラウド対応メモツールです。メールアドレスを使わずにユーザー名でログインでき、さらにワンクリックの Google ログインにも対応。ログインすると PC とスマホで同じアカウントが共有され、リアルタイムにメモが反映されます。軽快な UI に加え、安心の認証と自動バックアップ機能を備えた、日常使いにぴったりの Web メモアプリです。",
    imageUrl: "/memo.png",
    imageUrl_sp: "/memo_s.png",
    externalUrl: "https://memoapp-5rh.pages.dev/",
    technologies: ["React", "Create React App", "Testing Library", "Jest"],
  },
  {
    id: 4,
    title: "Part-time Shift",
    description: "スマホに最適化されたフルスタックのシフト管理アプリ。日付と勤務時間を登録すると、ダッシュボードで次の勤務や今月の労働時間・給与見込みを自動集計。カレンダー表示や csv エクスポートにも対応し、自分の予定をまとめて管理できます。",
    imageUrl: "/parttime_shift.png",
    imageUrl_sp: "/parttime_shift_s.png",
    externalUrl: "https://parttime-shift.pages.dev/",
    technologies: ["React", "TypeScript", "Vite", "Material UI", "Flask", "SQLite", "FullCalendar"],
  },
  {
    id: 5,
    title: "総合映像研究会ホームページ",
    description: "高知大学・総合映像研究会の公式サイトです。サークルの雰囲気を一気に伝えるヒーローセクションやサイドバー、活動予定・BBS・コンタクトなどの複数セクションを整備し、Markdown で管理する活動レポートをトップの一覧と詳細ページに分離して運用できる構成にしています。",
    imageUrl: "/soueiken-hp.png",
    imageUrl_sp: "/soueiken-hp-s.png",
    externalUrl: "https://soueiken-hp.pages.dev/",
    technologies: ["React", "Create React App", "React Router DOM", "Fetch API", "カスタム CSS", "自作 Markdown レンダラー"],
  },
  {
    id: 6,
    title: "Moodle Enhancer for Kochi University",
    description: "高知大学 Moodle を快適に使うための Chrome 拡張。ダッシュボードやコース画面をダークテーマで再構成し、課題・イベントを色分けカードで強調。リソースを自動収集する「資料」タブやメディア保存ボタン、クイズ画面の視認性改善など、学習体験を底上げする施策をコンテンツスクリプトでまとめて提供しています。",
    imageUrl: "/moodle-enhancer.png",
    imageUrl_sp: "/moodle-enhancer.png",
    externalUrl: "https://chromewebstore.google.com/detail/moodle-dashboard-tweaks/jmnmogonkjhmhgcncebieodddgbaamfg",
    technologies: ["Chrome Extension (Manifest V3)", "JavaScript", "Content Script", "CSS"],
    imageVariant: "icon",
  },
  {
    id: 7,
    title: "Selection Charcount",
    description: "右クリックメニューから呼び出せる選択文字数カウンター。選択中テキストをコンテキストメニューイベントで受け取り、余分な空白や絵文字を除外した上で文字数を計算し、画面右下に浮遊パネルとして描画します。Service Worker ベースの background と scripting API を使って任意ページにインジェクトできるので、Web 上のライティングやレビューで即座にカウントできます。",
    imageUrl: "/selection_charcount.png",
    imageUrl_sp: "/selection_charcount.png",
    externalUrl: "https://chromewebstore.google.com/detail/selection-charcount/kmjbolcinnpdiokkieehndnmnbhnmokk",
    technologies: ["Chrome Extension (Manifest V3)", "JavaScript", "Chrome Scripting API"],
    imageVariant: "icon",
  },
];
